### ISSUE TITLE
Optimize Janusgraph pod JVM settings

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-infra#48]
So far we could achieve the best results with

```yaml
  Limits:
      cpu:     4
      memory:  6Gi
    Requests:
      cpu:     500m
      memory:  3Gi
```

*Note: There's a big diff between CPU reqs and limits. This is because my test setup over-commits heavily on CPUs so I can schedule a lot even with a cheapish 10-node setup. This way I don't have to  scale down idle pods when I need the CPUs elsewhere*

Nevertheless, to actually make use of the memory, the JVM needs to be configured as well. A good value seems to be: 
```
-Xms1024m -Xmx2048m -javaagent:/workspace/janusgraph/lib/jamm-0.3.0.jar -Dgremlin.io.kryoShimService=org.janusgraph.hadoop.serialize.JanusGraphKryoShimService
```

However, we can't set that in the helm chart yet, currently blocked by https://github.com/helm/charts/issues/11543
